### ISSUE TITLE
Remaining known issues with Guard

### ISSUE THREAD

**Issue by jdickey** [jdickey/crypt_ident#14]
Our `Guardfile` and Guard usage are still far from ideal.

Known problems include, but are not necessarily limited to:

- [ ] Our `minitest` Guard task _does not_ pick up changes to test files.
- [ ] Our `shell` Guard usage lumps together several activities, and does not fire on individual changes. (Only one `shell` Guard task may be active in a single `Guardfile` apparently.)
- [ ] The `shell` Guard task does not reliably fire on individual file changes.
- [ ] The `shell` Guard task apparently eats standard output from tasks that it runs.
- [ ] We use `shell` to run `flog`, since [`guard-flog` is broken due to lack of maintenance](https://github.com/pantsoptional/guard-flog/issues/3#issuecomment-442073471).
- [ ] We use `shell` to run `flay`, since [`guard-flay` is broken due to lack of maintenance](https://github.com/pantsoptional/guard-flay/issues/1).
- [ ] We use `shell to run `reek`, since [`guard-reek` is broken due to lack of maintenance](https://github.com/pantsoptional/guard-reek/issues/3).

"How can people use Guard", you might reasonably ask, "if maintenance for so many of its plugins died 3-4 years ago?" The answers seems to be that (a) many non-Ruby-development Guard plugins *are* actively maintained, and (b) Ruby dev usage seems to now be limited to the `minitest` and `rake` Guard plugins, which *are* reasonably well-maintained as of late 2018.

**Comment by jdickey** [comment]
Not going to fix this for the 0.1.0 release, or in all likelihood until after 1.0.0.

Anyone who wishes to submit any PRs addressing any or all of the problems noted above would find them *profusely and profoundly* appreciated.
